version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.1.36:31112
functions:
  generate-password:
    lang: python3-http-debian
    handler: ./generate-password
    image: ahmosys/generate-password:latest
    build_options:
      - libpq
    environment:
      DB_NAME: "cofrap"
      DB_USER: "cofrap"
      DB_HOST: "postgresql.default.svc.cluster.local"
      DB_PORT: 5432
    secrets:
      - postgres-password

  generate-2fa:
    lang: python3-http-debian
    handler: ./generate-2fa
    image: ahmosys/generate-2fa:latest
    build_options:
      - libpq
    environment:
      DB_NAME: "cofrap"
      DB_USER: "cofrap"
      DB_HOST: "postgresql.default.svc.cluster.local"
      DB_PORT: 5432
    secrets:
      - postgres-password
      - mfa-key

  auth-user:
    lang: python3-http-debian
    handler: ./auth-user
    image: ahmosys/auth-user:latest
    build_options:
      - libpq
    environment:
      DB_NAME: "cofrap"
      DB_USER: "cofrap"
      DB_HOST: "postgresql.default.svc.cluster.local"
      DB_PORT: 5432
    secrets:
      - postgres-password
      - mfa-key
