version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.1.95:31112
functions:
  generate-password:
    lang: python3-http-debian
    handler: ./generate-password
    image: generate-password:latest

