version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.1.95:31112
functions:
  generate-password:
    lang: python3-http-debian
    handler: ./generate-password
    image: generate-password:latest

  generate-2fa:
    lang: python3-http-debian
    handler: ./generate-2fa
    image: generate-2fa:latest

  auth-user:
    lang: python3-http-debian
    handler: ./auth-user
    image: auth-user:latest

