apiVersion: v1
kind: Service
metadata:
  name: cofrap-frontend-service
spec:
  selector:
    app: cofrap-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
  type: NodePort
